name: Github pull request labels

on:
  issue_comment:
    types: [created, edited]

permissions:
  contents: read
  pull-requests: write

jobs:
  skip-test-labeler:
    uses: redhat-openshift-ecosystem/github-workflows/.github/workflows/label-command.yml@ISV-4528
